export const scopingConfigs = [
  "web_app_domain_url",
  "finalize_methods",
  "send_welcome_email",
  "service_hours_for_prescheduling_departure_time_selection",
  "rider_billing_type",
  "rider_types",
  "enable_driver_breaks_control",
  "rider_last_name_format_for_driver_app_display",
  "show_rider_feedback_distribution_toggle",
  "allow_shared_phones",
  "voc_book_ride_enable_pickup_and_dropoff_notes",
  "support_travel_reasons",
  "available_payment_methods_configurations",
  "menu",
  "minimum_no_show_wait",
  "minimum_no_show_wait_early_arrival",
  "enable_spontaneous_breaks_in_prebooking",
  "enable_dynamic_breaks",
  "min_break_duration_in_seconds",
  "max_break_duration_in_seconds",
  "allow_driver_breaks",
  "allow_breaks_anywhere",
  "Calc No Show Wait For Early Arrival Based On Arrival Time",
  "On Demand Minimum No-Show Wait By Ride Type For Early Arrival",
  "On Demand No-Show Priority Order",
  "Prebooking Minimum No-Show Wait By Ride Type",
  "Prebooking Minimum No-Show Wait By Ride Type For Early Arrival",
  "Prebooking No-Show Priority Order",
  "No Show Timer Default Time (Seconds)",
  "Rider-Name-Trimming Schema-Type",
  "allow_public_transport_proposals",
  "min_request_distance",
  "admin_booking_types",
  "immediate_apply_threshold_minutes",
  "prescheduling_timeslot_delta_minutes",
  "allow_prescheduled_ride_recurring_requests",
  "prescheduling_days_limit",
  "series_renewal_duration_days",
  "end_recurring_policy",
  "renew_series_enabled",
  "shown_recurring_series_types",
  "block_edit_ride_by_rider",
  "prescheduling_arrival_minutes_cant_order",
  "prescheduling_arrival_minutes_cant_order_admin",
  "prescheduling_minutes_cant_order_admin",
  "prescheduling_minutes_cant_order",
  "waiting_list_threshold_in_min",
  "show_phone_button_in_rider_app",
  "max_distance_from_pickup_stop_point",
  "max_distance_from_dropoff_stop_point",
  "max_distance_from_stop_point",
  "max_distance_from_terminal_stop_point",
  "max_distance_from_break_terminal_stop_point",
  "min_driver_break_seconds",
  "max_driver_break_seconds",
  "driver_call_rider",
  "flex_no_activity_auto_end_shift",
  "polygonpermission",
  "concessiontype",
  "maskedphone",
  "enable_skip_billing_v2",
  "service_hours",
  "no_fee_max_no_show_delay",
  "allow_inter_modal_proposals",
  "allow_inter_modal_second_leg_proposals",
  "should_display_price_on_public_transport_proposal",
  "webview_configuration",
  "can_book_free_rides_without_pm",
  "require_billing_for_proposals",
  "login_configurations",
  "importer_type",
  "operating_days",
  "web_app_domain_url",
  "passenger_count_change_enabled_with_plus_one_types",
  "allow_rider_call_through",
  "commitment_type",
  "finalize_methods",
  "ras_only_concession",
  "concessions",
  "polygon_blockers",
  "available_plus_one_types",
];
